Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "jenkins"
  config.vm.network :forwarded_port, guest: 9000, host: 9000, id: 'sonar', protocol: "tcp"
  config.vm.network :forwarded_port, guest: 8080, host: 38888, id: 'jenkins', protocol: "tcp"


  config.ssh.insert_key = false

  config.vm.define :jenkins do |jenkins|
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end


  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "files/ansible/playbook.yml"
    ansible.sudo = true
  end
end
