---
- name: Jenkins certificate training machine
  hosts: jenkins
  gather_facts: yes
  tasks:
      - name: installing repo for Java 8 in Ubuntu
        apt_repository: repo='ppa:openjdk-r/ppa'

- hosts: jenkins
  vars_files:
    - vars/main.yml
    - vars/jenkins.yml

  roles:
    - role: geerlingguy.firewall
    - role: geerlingguy.ntp
    - role: geerlingguy.git
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
    - role: geerlingguy.jenkins