---
- name: Jenkins certificate training machine
  hosts: all
  gather_facts: yes
  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'



  pre_tasks:
    - name: Override varaibles for MySQL (Debian)
      set_fact:
        mysql_packages:
          - mysql-server-5.6
      when: ansible_os_family == "Debian" and ansible_distribution_version == "14.04"

- hosts: all
  vars_files:
    - vars/main.yml
    - vars/jenkins.yml
    - vars/sonar.yml

  roles:
    - role: wtanaka.unzip
    - role: geerlingguy.firewall
    - role: geerlingguy.git
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
    - role: geerlingguy.jenkins
    - role: hylke1982.sonar

  post_tasks:
    - name: Update CA Java certificates
      command: /var/lib/dpkg/info/ca-certificates-java.postinst configure
      become: true