---
- name: Jenkins certificate training machine
  hosts: all
  gather_facts: yes
  tasks:
      - name: installing repo for Java 8 in Ubuntu
        apt_repository: repo='ppa:openjdk-r/ppa'

- hosts: all
  vars_files:
    - vars/main.yml
    - vars/jenkins.yml
    - vars/sonar.yml

  roles:
    - role: wtanaka.unzip
    - role: geerlingguy.firewall
    - role: geerlingguy.git
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
    - role: geerlingguy.jenkins
    - role: geerlingguy.sonar